version: 2

defaults:
  - version: main

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.10
  # If you have a requirements file, uncomment the next line
  # install:
  #   - requirements: requirements.txt
