version: 2

build:
  os: ubuntu-22.04          # Required: valid Ubuntu image
  tools:
    python: "3.10"          # Required: at least one tool

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt  # optional, if you have dependencies
