version: 2

defaults:
  - version: main

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt  # remove if you don't have this
