site_name: PythOS Documentation
site_url: https://pythos.readthedocs.io/
repo_url: https://github.com/PythOS-Official/
repo_name: GitHub
edit_uri: blob/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Getting Started: install.md
  - Usage: usage.md
  - Developer Guide: developer-guide.md
